### ISSUE TITLE
Popup comes up with an empty list

### ISSUE THREAD

**Issue by sebsto** [evandbrown/ami-cfn-mappings#1]
Hello,

Using latest version of http://aws.amazon.com/amazon-linux-ami, the popup presents an empty list - making the plugin unusable.

Seb

**Comment by sebsto** [comment]
This should be solved by this commit https://github.com/sebsto/ami-cfn-mappings/commit/16143861e0e9340c9576f0ed36906ea03937137f

I sent you a pull request for that one

Seb

**Comment by evandbrown** [comment]
Fixed in https://github.com/sebsto/ami-cfn-mappings/commit/16143861e0e9340c9576f0ed36906ea03937137f. Thanks, @sebsto!
