### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by stevemorad** [evandbrown/ami-cfn-mappings#4]
http(s)://aws.amazon.com/amis/\* page redirects to Marketplace, so it can't be used by this plugin anymore.

http(s)://aws.amazon.com/amazon-linux-ami no longer has a "Launch Instance" dropdown or URL associated with each AMI (other than a link to Marketplace, which is already ignored).  So the script gives an error about not being able to parse the href RegEx at line 114.  It looks like the AMI table is still getting parsed properly, but there needs to be a new way to populate the AMI ID and region variables without parsing a URL.

**Comment by sebsto** [comment]
It should work now with the latest changes

**Comment by evandbrown** [comment]
Thanks guys! I've merged Seb's changes and added him as a contributor to the project.
